---
title: "OER Commons"
author: "Joshua Rosenberg"
output: html_document
date: "2022-12-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)

t <- read_rds("final-oer-commons-data.rds")

# library(rvest)
# standards <- "https://www.nextgenscience.org/overview-dci" %>% 
#   read_html() %>% 
#   html_nodes("#bootstrap-fieldgroup-accordion--accordion .even a") %>% 
#   html_text()
# 
# standards_1 <- standards %>% 
#   str_split("  ") %>% 
#   map_chr(~.[[1]])
# 
# standards_2 <- standards %>% 
#   str_split("  ") %>% 
#   map_chr(possibly(~.[[2]], NA))
# 
# tibble(standards_1, standards_2) %>% 
#   write_csv("standards.csv")

standards <- read_csv("standards.csv") %>% 
  mutate(code = tolower(code)) %>% 
  rename(standards = code)

t <- t %>% 
  distinct(unique_links, .keep_all = TRUE)

nrow(t) # 48496
```

## prop science

```{r}
t %>% 
  mutate(unique_id = n()) %>% 
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>% 
  nest(unique_id) %>% 
  distinct(unique_links) # 8937

8937/48496 # .184
### good representation of science
```


## prop subject

```{r}
t %>% 
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>% 
  group_by(subject) %>% 
  summarize(n = n(),
            mean_views = mean(views)) %>% 
  mutate(prop = n / 8937) %>% 
  arrange(desc(prop)) %>% 
  knitr::kable()
### lots of life science
```



## prop level

```{r}
t %>% 
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>% 
  unnest(level) %>% 
  mutate(level = str_trim(level),
         level = str_split(level, ", ")) %>% 
  unnest(level) %>% 
  group_by(level) %>% 
  summarize(n = n(),
            mean_views = mean(views)) %>% 
  mutate(level = str_trim(level)) %>% 
  filter(level %in% c("Preschool", "Lower Primary",
                      "Upper Primary", "Middle School",
                      "High School", "Community College / Lower Division",
                      "College / Upper Division", 
                      "Graduate / Professional",
                      "Career / Technical", 
                      "Adult Education")) %>% 
  mutate(prop = n / 8937) %>% 
  arrange(desc(n)) %>% 
  knitr::kable()

### different from TPT - more upper-level
```

## interactions

```{r}

t %>% 
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>%
  mutate(stars = as.integer(stars)) %>% 
  select(stars:comments) %>% 
  skimr::skim()
```


## materials

```{r}
t %>%
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>% 
  unnest(material_type) %>% 
  filter(material_type %in% c(
    "Activity/Lab",
    "Assessment",
    "Case Study",
    "Data Set",
    "Diagram/Illustration",
    "Full Course",
    "Game",
    "Homework/Assignment",
    "Interactive",
    "Lecture",
    "Lecture Notes",
    "Lesson", 
    "Lesson Plan",
    "Module",
    "Primary Source",
    "Reading", 
    "Simulation",
    "Student Guide",
    "Syllabus",
    "Teaching/Learning Strategy",
    "Textbook",
    "Unit of Study"
  )) %>% 
  unnest(material_type) %>% 
  filter(material_type != ", ") %>% 
  group_by(material_type) %>% 
  summarize(n = n(),
            mean_views = mean(views)) %>% 
  mutate(prop = n / 8937) %>% 
  arrange(desc(n)) %>% 
  mutate(prop = prop * 100,
         prop = round(prop, 1)) %>% 
  knitr::kable()

```

## date added

```{r}
t %>% 
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>% 
  unnest(date_added) %>% 
  mutate(date_added = lubridate::mdy(date_added)) %>% 
  mutate(year = lubridate::year(date_added)) %>% 
  group_by(year) %>% 
  summarize(n = n(),
            mean_views = mean(views)) %>%  
  mutate(prop = n / 8937) %>% 
  arrange(desc(year)) %>% 
  knitr::kable()
```
## license

```{r}
t %>% 
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>% 
  unnest(license) %>% 
  mutate(license = str_trim(license)) %>% 
  group_by(license) %>% 
  summarize(n = n(),
            mean_views = mean(views)) %>% 
  arrange(desc(n)) %>% 
  mutate(prop = n / 8937) %>% 
  filter(n >= 10) %>% 
  mutate(prop = prop * 100,
         prop = round(prop, 1)) %>% 
  knitr::kable()
```


## endorsements

```{r}
t %>% 
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>% 
  unnest(endorsements) %>% 
  mutate(endorsements = str_replace_all(endorsements, "\n                    ", "")) %>% 
  mutate(endorsements = str_trim(endorsements)) %>% 
  mutate(endorsements = str_replace_all(endorsements, "   ", " ")) %>% 
  group_by(endorsements) %>% 
  summarize(n = n(),
            mean_views = mean(views)) %>%  
  mutate(prop = n / 8937) %>% 
  arrange(desc(n)) %>% 
  knitr::kable()

length_zero <- function(x) {
  length(x) == 0
}

t$any_endorsements <- t$endorsements %>% 
  map_int(length)

t %>% 
  mutate(unique_id = n()) %>% 
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>% 
  distinct(unique_links, .keep_all = TRUE) %>% 
  group_by(any_endorsements) %>% 
  summarize(n = n(),
            mean_views = mean(views)) %>% 
    mutate(prop = n / 8937) %>% 
    mutate(prop = prop * 100,
         prop = round(prop, 1)) %>% 
  knitr::kable()
```


## standards

```{r}
t %>% 
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>% 
  unnest(standards) %>% 
  unnest(standards) %>%
  mutate(standards = tolower(standards)) %>% 
  filter(str_detect(standards, "ngss")) %>% 
  mutate(standards = str_sub(standards, start = 6)) %>% 
  mutate(standards = str_replace_all(standards, "\\.", "-")) %>% 
  mutate(standards = str_sub(standards, end = -3)) %>% 
  group_by(standards) %>% 
  summarize(n = n(),
            mean_views = mean(views)) %>%  
  left_join(standards) %>% 
  mutate(prop = n / 8937) %>% 
  arrange(desc(n)) %>% 
  knitr::kable()

t %>% 
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>% 
  unnest(standards) %>% 
  unnest(standards) %>%
  mutate(standards = tolower(standards)) %>% 
  filter(str_detect(standards, "ngss")) %>% 
  nrow()

tt <- t %>% 
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>% 
  distinct(unique_links, .keep_all = TRUE)

tt$standards %>% 
  map_int(length)

t %>% 
  unnest(subject) %>% 
  filter(subject %in% c("Applied Science", "Life Science", "Physical Science")) %>% 
  distinct(unique_links, .keep_all = TRUE) %>% 
  mutate(standards = tolower(standards)) %>% 
  mutate(any_ngss = str_count(standards, "ngss")) %>% View()
  mutate(any_ngss = ifelse(any_ngss > 1, 2, any_ngss)) %>% 
  group_by(any_ngss) %>% 
  summarize(n = n(),
            mean_views = mean(views)) %>% 
    mutate(prop = n / 8937) %>% 
    mutate(prop = prop * 100,
         prop = round(prop, 1)) %>% 
  mutate(mean_views = round(mean_views, 1)) %>% 
  select(any_ngss, n, prop, mean_views) %>% 
  knitr::kable()
```

```{r}
2
```